// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qucssaxqbamjgbqslxtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1Y3NzYXhxYmFtamdicXNseHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MzM0NTAsImV4cCI6MjA3MzIwOTQ1MH0.HpynHkuPcxiAE9VKMKwrgBErY0xsJDoDTbpA3ia-_P4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});